name: build and deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    uses: oleksiyrudenko/gha-git-credentials@v2-latest
        with:
          token: "${{ secrets.GH_TOKEN }}"
    name: Setup Environment
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 16

      - name: Install Dependencies
        run: yarn install

      - name: Deploy to GitHub Pages
        run: yarn deploy
